const TITLES = [
  'Department of Competitive Integrity',
  'Bureau of Athletic Standards',
  'Commission for Racing Oversight',
  'Secretariat of Sports Regulation',
  'Authority for Event Governance',
  'Ministry of Physical Performance',
  'Council for Technical Compliance',
  'Office of Competition Adjudication',
  'Board of Racing Statistics',
  'Department of Participant Accreditation',
  'Agency for Sporting Verification',
  'Commission on Race Operations',
  'Bureau of Performance Monitoring',
  'Secretariat for Competitive Fairness',
  'Ministry of Athletic Records',
  'Office of Event Sanctioning',
  'Council for Regulatory Enforcement',
  'Department of Race Logistics',
  'Authority for Sports Integrity',
  'Bureau of Official Results and Records',
  'Ministere de la Rectification des Resultats Sportifs',
  'Commission Nationale de Verification des Classements',
  "Secretariat a l'Integrite des Competitions",
  'Autorite de Regulation des Donnees de Course',
  "Bureau d'Arbitrage des Litiges Sportifs",
  'Direction de la Conformite des Epreuves',
  "Conseil Superieur de l'Homologation des Resultats",
  'Agence de Revision des Performances et Chronometrage',
  'Office de Certification des Classements Officiels',
  "Departement de l'Audit des Resultats de Competition",
  'Inspection Generale des Donnees Sportives',
  'Comite de Validation des Feuilles de Course',
  'Service de Correction des Erreurs de Classement',
  'Secretariat a la Transparence des Resultats',
  'Bureau de Suivi des Litiges de Chronometrage',
  'Commission de Revision des Performances',
  'Direction de la Supervision des Classements',
  'Autorite de Controle des Resultats de Course',
  'Office de Rectification des Donnees de Competition',
  "Conseil d'Appel pour la Verification des Scores",
];

export function toWhomItMayConcern(): string {
  return TITLES[Math.floor(Math.random() * TITLES.length)];
}